require("betoharres.functions")
require("betoharres.settings")
require("betoharres.remap")
require("betoharres.setup-lsp")
require("betoharres.autocompletion")
require("betoharres.autoformat")
require("betoharres.fzf")
require("betoharres.gitgutter")
